### ISSUE TITLE
add check for cart changes in pulp

### ISSUE THREAD

**Issue by hzgraham** [abutcher/juicer#10]
if a cart is repushed and the previously pulled cart differs from what is in the database, have a check to verify and send a warning or error if trying to do a push

**Comment by abutcher** [comment]
I like the idea of overwriting existing carts because how many names can we come up with?

Some ideas:
Don't overwrite by default. Throw a warning and tell the user to use -f next time.
Prompt the user to overwrite existing cart.
Add some metadata to the cart like owner and date. Separate the carts using this metadata.

@hzgraham what do you think makes sense for using this during a release where multiple people are updating the remote cart?
