### ISSUE TITLE
Support fnmatch.fnmatch suffix matching for remote apache file indexes with a default of *.rpm

### ISSUE THREAD

**Issue by abutcher** [abutcher/juicer#24]
When we're matching remote files in an apache file index, we grab anything with a `.anything` rather than `.rpm` as we did before. Here is an example listing:

```
...
<li><a href="somepackage.rpm"> somepackage.rpm</a></li>
<li><a href="sometext.txt"> sometext.txt</a></li>
<li><a href="whatever.png"> whatever.png</a></li>
...
```

If we did a `juicer cart create name -r repo http://the-above-listing.com/listing/`, we would get all of those files and pushing them to an rpm repository would appear to be successful but only `somepackage.rpm` would be imported by pulp. If we pushed these to an iso repo, every file would be imported successfully.

**Comment by abutcher** [comment]
Maybe cart creation checks the remote repo type and uses that to determine what types of files to include?

**Comment by tbielawa** [comment]
Hmmmmmmm.... The firs thing I thought of with this suggested change is that is means cart creation requires an "always-on" connection, if it is going to check the target repository type first.

I offer the following proposal to slightly modify your original idea.

It sounds like we want to **expand** the items which can be added to a cart when using the directory-index method. The problem is that we can't just say 'add all the things!' without adding illegal items (determined by the type of items which the target repository accepts) into the cart.

I think the following might be a sane alternative which provides much of the same functionality:

# Current Behavior

    juicer cart create foobar -r myrepo http://the-above-listing.com/listing/

All ``*.rpm`` items are added to the cart. We might try **rethinking** how we define this exact behavior.

# Re-defining the behavior
In the previous example, a user *interacting with an RPM* repository, the user **expects the action of creating his cart** to mean the cart will only include ``*.rpm`` files.

We can satisfy the users expectations even if we change how this behavior works behind the scenes (in any way we wish) as long **as the users expected results are met**. *Kind of like* re-factoring code in a non-API breaking way. The entry-points are the same, and the results are the same, it's the stuff in the middle that changes.

Back to the users expectations...

What if the *item spec* (*item spec* is what we refer to the ``<ITEMS>`` given when using ``cart create NAME -r repo_name <ITEMS> ...`` -- such as: filesystem paths, directory indexs, and specific remote rpms) supported [fnmatch.fnmatch](https://docs.python.org/2/library/fnmatch.html#fnmatch.fnmatch) style matching in the case of *remote items*?

**Furthermore**, what if this globbing mechanism defaulted to matching ``*.rpm`` items? After-all, this functionality **already has* an explicit filter for just ``*.rpm`` items. 

If we change the behavior to allow user-specified globs, and maintain the current default globbing behavior, then the user's expectations are satisfied. Additionally, this opens the door to accepting arbitrary match strings for future use-cases.

# Examples

## Set-up

The directory index at http://frob.nicate.com/rpms/ contains the following items:

* megafrobber.noarch.rpm
* README.txt
* test.html

## Current behavior (doesn't break!)

Current **default** behavior would not change at all:

    juicer cart create frobber -r megafrob http://frob.nicate.com/rpms/

The cart would only contains items which matched ``*.rpm`` from the directory index. To be explicit, this means the cart would contain one single item: ``megafrobber.noarch.rpm``

## New Behavior (match other suffix)

Let's presume the user is creating a cart for an ``ISO`` repository. This user only wishes to include ``.txt`` files in their RPM:

    juicer cart create frobreader -r megafrobdocs 'http://frob.nicate.com/rpms/*.txt'

**NOTE** how the items spec is wrapped in **single quotes**. This may (will?) be required due to side-effects of shell interpolation.

## New Behavior (match ANY suffix)

Again, let's presume the user is creating a cart for an ``ISO`` repository. This user wishes to include **all files** from the directory listing:

    juicer cart create frobreader -r megafrobdocs 'http://frob.nicate.com/rpms/*'

## New Behavior (match two suffixs)

Again (yes, again), let's presume the user is creating a cart for an ``ISO`` repository. This user wishes to include only ``.txt`` and ``.html`` files from the directory listing:

    juicer cart create frobreader -r megafrobdocs 'http://frob.nicate.com/rpms/*.txt' 'http://frob.nicate.com/rpms/*.html'

The created cart would only include items from the directory index which matched either the glob ``*.txt`` or ``*.html``.

@abutcher have you any thoughts on this? Just spit-ballin' here.

**Comment by abutcher** [comment]
@tbielawa +1. I like this and it's a big improvement to defaulting to any suffix and also keeps cart creation offline wrt pulp. Nice.

**Comment by tbielawa** [comment]
This could be a fun one to program.

**Comment by tbielawa** [comment]
oh dang
